### ISSUE TITLE
How can I translate kinds of pets?

### ISSUE THREAD

**Issue by DoctorChe** [jllorencetti/pets#56]
Hi!
I am trying to translate this app to Russian.
Almost all is good.
But I do not understand how is it possible to translate kins of pets.

**Comment by jllorencetti** [comment]
Hi @DoctorChe 

Kind is a regular Django model, you can edit, create, delete kinds using the Django Admin interface.

Could you be a bit more specific about this issue?
Maybe highlighting the line code or code block that is causing trouble.

Thanks.
